### ISSUE TITLE
Module Settings support

### ISSUE THREAD

**Issue by akrigline** [Haxxer/FoundryVTT-PotatoOrNot#1]
There are modules which have settings that could benefit from a similar treatment from this one. Off the top of my head two examples:

- My own [ImageFog](https://github.com/ElfFriend-DnD/foundryvtt-imageFog) has what I refer to as "performance mode" useful for Shitty Potato tier computers.
- [Dice So Nice](https://gitlab.com/riccisi/foundryvtt-dice-so-nice) has a plethora of settings and even might recommend being turned off entirely for the lowest end machine.

Strategies for how to accomplish this, I see two:
1. Provide an API for external modules to register themselves and their own recommended settings at each tier. Putting this on `window` and calling a `PotatoOrNotReady` hook during `init` would be the best way to accomplish this I believe.

2. Encourage PRs or Issues and manage this yourself.

**Comment by Haxxer** [comment]
Added `PotatoOrNotReady` hook in 0.2.0, along with ability to easily add settings to quality levels
