### ISSUE TITLE
Why isn't this listed in official modules? 

### ISSUE THREAD

**Issue by edzillion** [Haxxer/FoundryVTT-PotatoOrNot#3]
I was hoping to use this as part of my module `blood-n-guts` to set performance settings appropriately but that will be too convoluted without the mod listed in the official tracker.

**Comment by Haxxer** [comment]
Good question. I'll look into going official - even though this module still has pending art.

**Comment by Haxxer** [comment]
It has been submitted.

**Comment by Haxxer** [comment]
https://foundryvtt.com/packages/potato-or-not
