### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by brunocalado** [Haxxer/FoundryVTT-PotatoOrNot#4]
Hi.

How can I add translation to Portuguese?

Thank you.

**Comment by Haxxer** [comment]
No way currently, but I'll add localization support in the next update.

**Comment by brunocalado** [comment]
tks

**Comment by Haxxer** [comment]
I added localization support in 0.4.0. [This page](https://foundryvtt.com/article/localization/) will explain the basics, and if you want to create a pull request to add another language, feel free!

**Comment by brunocalado** [comment]
{
	"PotatoOrNot.BadTitle": "Computador da Xuxa com Gripe",
	"PotatoOrNot.BadDescription": "Caso tenha um notebook ou computador mais simples, use essas configurações para uma melhor experiência!",
	"PotatoOrNot.MediumTitle": "Computador da Xuxa",
	"PotatoOrNot.MediumDescription": "Você tem um computador mediano que não é ruim, mas já não aguenta tanto.",
	"PotatoOrNot.GoodTitle": "Computador da Nasa",
	"PotatoOrNot.GoodDescription": "Seu computador é excelente.",
	"PotatoOrNot.Selection": "Selecione o nível de qualidade do seu computador:",
	"PotatoOrNot.Accept": "Okay"
}

**Comment by Haxxer** [comment]
Thank you for your contribution, but another translation already made it in with [#5](https://github.com/Haxxer/FoundryVTT-PotatoOrNot/pull/5)!
